/**
 * \file
 *
 * \brief Driver initialization.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include "driver_init.h"
#include <system.h>

/* Configure pins and initialize registers */
void ADC_0_initialization(void)
{

	Xp_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	Xp_set_pull_mode(PORT_PULL_OFF);

	Yp_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	Yp_set_pull_mode(PORT_PULL_OFF);

	Xm_set_level(false);
	Xm_set_dir(PORT_DIR_OFF);
	Xm_set_pull_mode(PORT_PULL_OFF);
	Xm_set_inverted(false);
	Xm_set_isc(PORT_ISC_INTDISABLE_gc);
	
	Ym_set_level(false);
	Ym_set_dir(PORT_DIR_OFF);
	Ym_set_pull_mode(PORT_PULL_OFF);
	Ym_set_inverted(false);
	Ym_set_isc(PORT_ISC_INTDISABLE_gc);

	ADC_0_init();
}

void TIMER_0_initialization(void)
{

	TIMER_0_init();
}

/* configure pins and initialize registers */
void I2C_0_initialization(void)
{

	PB0_set_level(false);
	PB0_set_dir(PORT_DIR_OUT);
	PB0_set_pull_mode(PORT_PULL_OFF);
	PB0_set_inverted(false);
	PB0_set_isc(PORT_ISC_INTDISABLE_gc);

	PB1_set_level(false);
	PB1_set_dir(PORT_DIR_OUT);
	PB1_set_pull_mode(PORT_PULL_OFF);
	PB1_set_inverted(false);
	PB1_set_isc(PORT_ISC_INTDISABLE_gc);

	I2C_0_init();
}

/**
 * \brief System initialization
 */
void system_init()
{
	mcu_init();
	
	/* PORT setting on PA5 */

	R0_set_level(true);
	R0_set_dir(PORT_DIR_OUT);
	R0_set_pull_mode(PORT_PULL_OFF);
	R0_set_inverted(false);
	R0_set_isc(PORT_ISC_INTDISABLE_gc);

	/* PORT setting on PA4 */

	R1_set_level(true);
	R1_set_dir(PORT_DIR_OUT);
	R1_set_pull_mode(PORT_PULL_OFF);
	R1_set_inverted(false);
	R1_set_isc(PORT_ISC_INTDISABLE_gc);

	/* PORT setting on PA3 */

	R2_set_level(true);
	R2_set_dir(PORT_DIR_OUT);
	R2_set_pull_mode(PORT_PULL_OFF);
	R2_set_inverted(false);
	R2_set_isc(PORT_ISC_INTDISABLE_gc);

	/* PORT setting on PA2 */

	R3_set_level(true);
	R3_set_dir(PORT_DIR_OUT);
	R3_set_pull_mode(PORT_PULL_OFF);
	R3_set_inverted(false);
	R3_set_isc(PORT_ISC_INTDISABLE_gc);
	
	/* PORT setting on PA1 */

	R4_set_level(true);
	R4_set_dir(PORT_DIR_OUT);
	R4_set_pull_mode(PORT_PULL_OFF);
	R4_set_inverted(false);
	R4_set_isc(PORT_ISC_INTDISABLE_gc);

	/* PORT setting on PB2 */

	C0_set_level(false);
	C0_set_dir(PORT_DIR_IN);
	C0_set_pull_mode(PORT_PULL_UP);
	C0_set_inverted(false);
	C0_set_isc(PORT_ISC_INTDISABLE_gc);

	/* PORT setting on PB6 */

	C1_set_level(false);
	C1_set_dir(PORT_DIR_IN);
	C1_set_pull_mode(PORT_PULL_UP);
	C1_set_inverted(false);
	C1_set_isc(PORT_ISC_INTDISABLE_gc);

	/* PORT setting on PB5 */

	C2_set_level(false);
	C2_set_dir(PORT_DIR_IN);
	C2_set_pull_mode(PORT_PULL_UP);
	C2_set_inverted(false);
	C2_set_isc(PORT_ISC_INTDISABLE_gc);

	/* PORT setting on PB7 */

	C3_set_level(false);
	C3_set_dir(PORT_DIR_IN);
	C3_set_pull_mode(PORT_PULL_UP);
	C3_set_inverted(false);
	C3_set_isc(PORT_ISC_INTDISABLE_gc);

	/* PORT setting on PB4 */

	C4_set_level(false);
	C4_set_dir( PORT_DIR_IN);
	C4_set_pull_mode(PORT_PULL_UP);
	C4_set_inverted(false);
	C4_set_isc(PORT_ISC_INTDISABLE_gc);

	/* PORT setting on PB3 */

	C5_set_level(false);
	C5_set_dir(PORT_DIR_IN);
	C5_set_pull_mode(PORT_PULL_UP);
	C5_set_inverted(false);
	C5_set_isc(PORT_ISC_INTDISABLE_gc);

	/* PORT setting on PC5 */

	// Set pin direction to output

	KEY_INT_set_level(false);
	KEY_INT_set_dir(PORT_DIR_OUT);

	CLKCTRL_init();

	Timer_init();

	ADC_0_initialization();

	TIMER_0_initialization();

	CPUINT_init();

	SLPCTRL_init();

	I2C_0_initialization();

	BOD_init();
}
