#ifndef DRV_NAU8810_I2S_PARAMS_H
#define DRV_NAU8810_I2S_PARAMS_H

///////////////////////////////////////////////////////////////////////
//////////////// Header file generated by tools/i2s.py //////////////// 
///////////////////////////////////////////////////////////////////////

#define DRV_NAU8810_MCK NRF_I2S_MCK_32MDIV8
#define DRV_NAU8810_RATIO NRF_I2S_RATIO_256X
#define DRV_NAU8810_PLLN 12
#define DRV_NAU8810_PLLK1 0
#define DRV_NAU8810_PLLK2 0
#define DRV_NAU8810_PLLK3 0
#define DRV_NAU8810_MCLKSEL 3
#define DRV_NAU8810_PLLM 0
#define DRV_NAU8810_LRCK 15625

#endif
