image: bm-badge:latest

volumes:
        /home/dc801/dev/BM-Badge:
                hostpath: "$PWD/../../"
                options: rw

aliases:
        desktop:
                script:
                        - cd /home/dc801/dev/BM-Badge/Software/GameEngine
                        - compiledb make DESKTOP=1 -j`nproc`
        embedded:
                script:
                        - cd /home/dc801/dev/BM-Badge/Software/GameEngine
                        - compiledb make EMBEDDED=1 -j`nproc`
        clean: make cleanall -j`nproc`
        cleanall: make cleanall -j`nproc`
        flash:
                docker_args: --privileged -v /dev:/dev
                script:
                        - cd /home/dummy/dev/BM-Badge/Software/GameEngine
                        - compiledb make flash EMBEDDED=1 -j`nproc`
        gdbserver:
                docker_args: --privileged -v /dev:/dev -p 2331:2331
                script:
                        - JLinkGDBServer -device nrf52 -if SWD -speed 4000
        jlink:
                docker_args: --privileged -v /dev:/dev
                script:
                        - JLinkExe -device nrf52 -if SWD -speed 4000 -autoconnect 1
